version: '3'
services:

  mysql:
    image: "mysql:5.7.10"
    ports:
      - '${FORWARD_DB_PORT}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "${FORWARD_PHPMYADMIN_PORT}:80"
    environment:
      PMA_HOST: 'mysql'
      PMA_USER: 'root'
      PMA_PASSWORD: '${DB_PASSWORD}'

  redis:
    image: 'redis:alpine'
    ports:
        - '${FORWARD_REDIS_PORT:-6379}:6379'
  